---
title: "PrePhage3 pre analysis"
date: "2023-04-17"
output: html_document
---

```{r setup, include=FALSE}
p1 <- c("tidyverse", "vegan", "BiocManager")
p2 <- c("phyloseq", "ANCOMBC", "DESeq2", "ComplexHeatmap","MicrobiotaProcess","ggsci","directlabels","ggpubr")
load_package <- function(p) {
  if (!requireNamespace(p, quietly = TRUE)) {
    ifelse(p %in% p1, 
           install.packages(p, repos = "http://cran.us.r-project.org/"), 
           BiocManager::install(p))
  }
  library(p, character.only = TRUE, quietly = TRUE)
}
invisible(lapply(c(p1,p2), load_package))

library(readxl)

```


```{r}
col_fil <- pal_jco("default")(10)

col_scale <- scale_color_jco()
```

#Build phyloseq object

```{r pressure, echo=FALSE}
otu <- read.table(file = "otu_prephage3_colon17042023.txt", sep = "\t", header = T, row.names = 1, 
                  skip = 0, comment.char = "")
taxonomy <- otu[,"taxonomy", drop = FALSE]
otu <- subset(otu, select = -taxonomy)

# clean the taxonomy, Greengenes format
tax <- taxonomy %>%
  select(taxonomy) %>% 
  separate(taxonomy, c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"), ";")

tax.clean <- data.frame(row.names = row.names(tax),
                        Kingdom = str_replace(tax[,1], "k__",""),
                        Phylum = str_replace(tax[,2], "p__",""),
                        Class = str_replace(tax[,3], "c__",""),
                        Order = str_replace(tax[,4], "o__",""),
                        Family = str_replace(tax[,5], "f__",""),
                        Genus = str_replace(tax[,6], "g__",""),
                        Species = str_replace(tax[,7], "s__",""),
                        stringsAsFactors = FALSE)

tax.clean[is.na(tax.clean)] <- ""
tax.clean[tax.clean=="__"] <- ""

for (i in 1:nrow(tax.clean)){
  if (tax.clean[i,7] != ""){
    tax.clean$Species[i] <- paste(tax.clean$Genus[i], tax.clean$Species[i], sep = " ")
  } else if (tax.clean[i,2] == ""){
    kingdom <- paste("Unclassified", tax.clean[i,1], sep = " ")
    tax.clean[i, 2:7] <- kingdom
  } else if (tax.clean[i,3] == ""){
    phylum <- paste("Unclassified", tax.clean[i,2], sep = " ")
    tax.clean[i, 3:7] <- phylum
  } else if (tax.clean[i,4] == ""){
    class <- paste("Unclassified", tax.clean[i,3], sep = " ")
    tax.clean[i, 4:7] <- class
  } else if (tax.clean[i,5] == ""){
    order <- paste("Unclassified", tax.clean[i,4], sep = " ")
    tax.clean[i, 5:7] <- order
  } else if (tax.clean[i,6] == ""){
    family <- paste("Unclassified", tax.clean[i,5], sep = " ")
    tax.clean[i, 6:7] <- family
  } else if (tax.clean[i,7] == ""){
    tax.clean$Species[i] <- paste("Unclassified ",tax.clean$Genus[i], sep = " ")
  }
}

metadata <- meta_cleaned

OTU = otu_table(as.matrix(otu), taxa_are_rows = TRUE)
TAX = phyloseq::tax_table(as.matrix(tax.clean))
SAMPLE <- sample_data(metadata)
# TREE = read_tree("tree.nwk")
# merge the data

ps <- phyloseq(OTU, TAX, SAMPLE)

saveRDS(ps, "ps.test.dbrda.rds")
```
#tax
```{r}
tax
```

#tax clean
```{r}
tax.clean
```

# Rarefaction curve
```{r}
# Extract the OTU table from the phyloseq object
mat <- t(otu_table(ps))

class(mat) <- "matrix"
class(mat)
# Calculate the total number of reads (samples)
raremax <- min(rowSums(mat))

# Create the rarefaction curve
rarecurve(mat, step = 100, sample = raremax, col = "blue", label = TRUE)
```


```{r}
set.seed(111) # keep result reproductive
ps.rarefied = rarefy_even_depth(ps, rngseed=1, sample.size=1000, replace=F)
meta_test <- sample_data(ps.rarefied)
meta_test$Group <- sub("FFT2","FFT",meta_test$Group)
meta_test$Group <- sub("FFT1","FFT",meta_test$Group)
meta_test$Group <- sub("Control2","Control",meta_test$Group)
meta_test$Group <- sub("Control1","Control",meta_test$Group)
sample_data(ps.rarefied)<-meta_test
saveRDS(ps.rarefied, "ps.rarefied.test.dbrda.rds")
#meta_test <- sample_data(ps.rarefied)
#meta_test$Group <- sub("FFT2","FFT",meta_test$Group)
#meta_test$Group <- sub("FFT1","FFT",meta_test$Group)
#meta_test$Group <- sub("Control2","Control",meta_test$Group)
#meta_test$Group <- sub("Control1","Control",meta_test$Group)
#sample_data(ps.rarefied)<-meta_test
#print(ps.rarefied)
#print(meta_test)

```



# Alpha diversity

## By Treatment of pig
```{r, eval = T, include = T, echo = F, message = F, warning=FALSE}

ps_no_control_rec <- subset_samples(ps.rarefied, Group %in% c("Control", "FFT"))

#Normalize to mean read count
standf = function(x, t=total) round(t * (x / sum(x)))
total = median(sample_sums(ps_no_control))
PSB.R = transform_sample_counts(ps_no_control, standf)

#Set desired alpha diversity metrics

alpha_met <- c("Observed","Shannon")

variable <- c("Group")


alpha.Treatment <- plot_richness(PSB.R, measures=alpha_met , x=variable, color=variable) + 
  geom_boxplot(alpha=0.1, lwd = 0.5) +
  ggtitle(bquote(bold("Shannon and Observed diversity as a measure for Alpha Diversity"))) +
  scale_color_jco() +
  theme_classic() +
  theme(text = element_text(size = 8),
        axis.line=element_line(size=1),
        axis.text=element_text(size = 8, colour = "Black"),
        axis.ticks=element_line(size=1, colour = "Black"),
        strip.background = element_rect(colour = "white", fill = "white"),
        axis.text.x=element_text(angle = 45, hjust = 1),
        strip.text.x = element_text(size = 8, angle = 0),
        legend.text = element_text(size = 8)
  ) +
                  scale_color_manual(
                    values=c("#e34a33", "#31a354"),
                    breaks = c( "Control", "FFT"),
                    labels = c( "Control", "FFT")
                  )+
  labs(x="Group",
       y="Alpha diversity")


alpha.Treatment

```



```{r}
library(ggplot2)
library(dplyr)

meta_cleaned <- read.table("Meta_cleaned.txt", sep="\t", header=TRUE)

# Add new column 'NEC_incidence' with blank values
meta_cleaned <- meta_cleaned %>%
  mutate(NEC_incidence = "") %>%
  select(-5) %>%
  mutate(Group = case_when(
    Group %in% c("FFT1", "FFT2") ~ "FFT",
    Group %in% c("Control1", "Control2") ~ "Control",
    TRUE ~ as.character(Group)
  ))

# Update the 'NEC_incidence' column based on 'Colon_score'
meta_cleaned$NEC_incidence <- ifelse(meta_cleaned$Colon_score >= 4, "NEC", "No NEC")

# Create a boxplot with scatter points
ggplot(filtered_meta, aes(x = Group, y = Growth, fill = Group)) +
  geom_boxplot(alpha = 0.8) +
  geom_jitter(width = 0.2, height = 0) +
  scale_fill_manual(values = c("steelblue", "firebrick3"), labels = c("Control", "FFT")) +
  labs(x = "Treatment", y = "Growth (g/day)") +
  ggtitle("Boxplot of Growth per day by Treatment Type") +
  theme_minimal() +
  theme(legend.position = "right")

# Subset the metadata dataset for 'FFT' and 'Control' groups
fft_data <- metadata[metadata$Group == "FFT", "Growth"]
control_data <- metadata[metadata$Group == "Control", "Growth"]

# Perform Welch's t-test
result <- t.test(fft_data$Growth, control_data$Growth, var.equal = FALSE)

# Print the t-test results
print(result)

```


## Statistics
```{r}
rich = estimate_richness(ps_no_control, measures = c("Observed", "Shannon"))
wilcox.observed <- pairwise.wilcox.test(rich$Observed, 
                                        sample_data(ps_no_control)$Group, 
                                        p.adjust.method = "BH")
tab.observed <- wilcox.observed$p.value %>%
  as.data.frame() %>%
  tibble::rownames_to_column(var = "group1") %>%
  gather(key="group2", value="p.adj", -group1) %>%
  na.omit()
tab.observed
```

```{r}
wilcox.shannon <- pairwise.wilcox.test(rich$Shannon, 
                                       sample_data(ps_no_control)$Group, 
                                       p.adjust.method = "BH")
tab.shannon <- wilcox.shannon$p.value %>%
  as.data.frame() %>%
  tibble::rownames_to_column(var = "group1") %>%
  gather(key="group2", value="p.adj", -group1) %>%
  na.omit()
tab.shannon
```

#Beta diversity
## With reference ID
```{r, eval = T, include = T, echo = F, massage = F}
##Do PCoA ordination based on Bray-curtis distance
GP.ord_bray <- ordinate(ps_no_control, "PCoA", "bray")

beta.id_bray <- phyloseq::plot_ordination(ps_no_control, GP.ord_bray, color="Group") + 
  geom_point(aes(shape = Litter), size = 3) +
  theme_classic() + 
  theme(plot.title = element_text(size = 12, face = "bold",hjust = 0.5),
        strip.background = element_blank(),
        strip.text.x = element_blank()) + 
  scale_x_reverse() +
  ggtitle("Beta Diversity using Bray-Curtis")

beta.id_bray

#
anova_bray <- data.frame(phyloseq::sample_data(ps_no_control))

dist = phyloseq::distance(ps_no_control, method="bray")
anova_bray$Group <- factor(anova_bray$Group, levels = c("Control", "FFT"))

test.adonis <- vegan::adonis2(t(ps_no_control@otu_table) ~ Group, data = anova_bray, method = "bray")
test.adonis

```

## Beta diversity jaccard
```{r}
#Do PCoA ordination based on Bray-curtis distance
GP.ord_jaccard <- ordinate(ps_no_control, "PCoA", "jaccard")

beta.id_jaccard <- phyloseq::plot_ordination(ps_no_control, GP.ord_jaccard, color="Group") + 
  geom_point(aes(shape = Litter), size = 3) +
  theme_classic() + 
  theme(plot.title = element_text(size = 12, face = "bold",hjust = 0.5),
        strip.background = element_blank(),
        strip.text.x = element_blank()) + 
  scale_x_reverse() +
  ggtitle("Beta Diversity using Jaccard")

beta.id_jaccard 

#Anova/Adonis
dist = phyloseq::distance(ps_no_control, method="jaccard")
anova_jac$Group <- factor(anova_jac$Group, levels = c("Control", "FFT"))

anova_jac <- data.frame(phyloseq::sample_data(ps_no_control))

test.adonis <- vegan::adonis2(t(ps_no_control@otu_table) ~ Group, data = anova_jac, method = "jaccard")
test.adonis

vegan::betadisper(test.adonis )

test.adonis <- as.data.frame(test.adonis$aov.tab)
test.adonis

scores(test.adonis, display = "site")

```

## Group：axis1：2
```{r, eval = T, include = T, echo = F, message = F}
beta.treatment = phyloseq::plot_ordination(ps_no_control, GP.ord, axes = 1:2,color="Group") +
  stat_ellipse(aes(colour = Group), geom = "polygon", level = 0.95, fill = NA, size = 1) +
  scale_color_manual(values=c("#F27970","#32B897"), breaks = c("Control", "FFT"), labels = c("Control", "FFT")) +
  geom_point(aes(shape = ifelse(Litter == "Litter1", "Litter1", "Litter2"), size = 0.5)) +
  guides(shape = guide_legend(title = "Litter"), size = FALSE) +
  theme_classic() + 
  theme(plot.title = element_text(size = 12, face = "bold",hjust = 0.5),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10)) + 
  scale_x_reverse() +
  ggtitle("Beta diversity between litter and treatment groups")

beta.treatment
```
## Treatment group with only Control1 and FFT1
```{r, eval = T, include = T, echo = F, message = F}
#Keep true samples
ps_no_control <- subset_samples(ps.rarefied, Group %in% c("Control","FFT"))
GP.ord <- ordinate(ps_no_control, "PCoA", "bray")

beta.treatment = phyloseq::plot_ordination(ps_no_control, GP.ord, axes = 1:2,color="Group") +   #Change axes to 2:3 3:4 4:5 and see how the other dimensions look

  #Change 'color' to litter or another column name to 
  stat_ellipse(geom = "polygon", level = 0.95, fill = NA, size = 1) +              
  scale_color_jco() +
  theme_classic() + 
  theme(plot.title = element_text(size = 12, face = "bold",hjust = 0.5),          #set the font and size of the text
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10)
  ) + 
  # geom_point(size = 3) +
  scale_x_reverse() +# Revert x-axis to match plots
  ggtitle("Bacteriome")+
  scale_color_manual(
                    values=c("#F27970","#BB9727"),           #set certain color for the groups
                    breaks = c( "Control1", "FFT1"),
                    labels = c( "Control1", "FFT1")
                    )

beta.treatment
```

# Abundance barplot
## Individual sample barplots.
```{r, eval = T, include = T, echo = F, message = F}

bac.phyl <- tax_glom(ps, "Genus", NArm = FALSE)

ps0 <- transform_sample_counts(bac.phyl, function(x) x / sum(x))

#Create melted dataframe
df <- psmelt(ps0)

#Select last non-empty taxonomic rank
df[df==""] <- NA

df$tax <- apply(df, 1, function(x) tail(na.omit(x), 1))

#Arrange samples by mean abundance
top <- df %>%
  group_by(Reference_ID, Litter,tax) %>%
  dplyr::summarize(Mean = mean(Abundance)) %>%
  arrange(-Mean)
#Show top
#top

top10 <- top$tax[1:150]
df0 <- df %>%
  mutate(tax = fct_other(tax, c(as.matrix(top10))))

df0 <- df0[order(df0$Sample, decreasing = TRUE), ]

barplot.all.samples <- ggplot(df0, aes(Reference_ID, Abundance, fill = fct_reorder(tax, Abundance, .fun = mean))) + 
  geom_col(width = 0.8) +
  #facet_wrap("Group")+
  scale_fill_jco(name = "Taxonomy") +
  scale_fill_manual(values=rep(col_fil,5),name="Genus")+
  theme_classic() +
  theme(text = element_text(size = 10, colour = "Black"),
        axis.line=element_line(size=0.5),
        #panel.border = element_blank(),
        axis.text=element_text(size = 10, colour = "Black"),
        axis.ticks=element_line(size=1, colour = "Black"),
        strip.background = element_rect(colour = "white", fill = "white"),
        axis.text.x=element_text(angle = 45, hjust = 1),
        strip.text.x = element_text(angle = 0, size=12, face = "bold"),
        #legend.position = "none"
  ) +
  ylab("Relative abundance")


barplot.all.samples

```


# NEC incidence
```{r}
library(dplyr)

NEC_df <- read.table("NEC.txt", sep="\t", header=TRUE)

NEC_table <- NEC_df %>% 
  mutate(Treatment = ifelse(grepl("FFT", Treatment), "FFT", "Control"),
         Nec_incidence = ifelse(NEC_score >= 4, "NEC", "No Nec")) %>%
  group_by(Treatment, Nec_incidence) %>%
  summarize(count = n()) %>%
  pivot_wider(names_from = Nec_incidence, values_from = count) %>%
  mutate(Total = NEC + `No Nec`) %>%
  mutate(Nec_percentage = round((NEC / Total) * 100, 2)) %>%
  select(Treatment, NEC, `No Nec`, Total, Nec_percentage)

colnames(NEC_table) <- c("Treatment", "NEC Incidence", "No NEC Incidence", "Total Amount of Pigs", "NEC Percentage")

# Format the table for printing
NEC_table %>%
  knitr::kable(format = "html", align = "c", caption = "NEC Incidence Compared Between Treatment Groups") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)



# Subset the data for the two treatment groups
FFT_scores <- NEC_df$NEC_score[grepl("FFT", NEC_df$Treatment)]
Control_scores <- NEC_df$NEC_score[!grepl("FFT", NEC_df$Treatment)]

# Perform a t-test
t.test(FFT_scores, Control_scores)

ggsave()


```

# Leukocytes
```{r}
library(dplyr)
library(ggplot2)

# Filter data for FFT group
fft_leuk <- meta_leuk %>%
  filter(!is.na(Total_leukocytes)) %>%
  filter(Group == "FFT") %>%
  select(Group, Total_leukocytes)

# Filter data for Control group
control_leuk <- meta_leuk %>%
  filter(!is.na(Total_leukocytes)) %>%
  filter(Group == "Control") %>%
  select(Group, Total_leukocytes)

# Remove missing values from Total_leukocytes and convert to numeric
meta_leuk$Total_leukocytes <- as.numeric(meta_leuk$Total_leukocytes)
meta_leuk <- meta_leuk[complete.cases(meta_leuk$Total_leukocytes),]

# Create boxplot
ggplot(meta_leuk, aes(x = Group, y = Total_leukocytes, fill = Group)) +
  geom_boxplot() +
  geom_jitter(width = 0.2, height = 0, color = "black", size = 2) +
  stat_summary(fun = mean, geom = "point", shape = 23, size = 3, fill = "white", color = "black") +
  scale_fill_manual(values = c("#0072B2", "#D55E00")) +
  labs(x = "Treatment", y = "Total Leukocytes", fill = "Treatment") +
  ggtitle("Boxplot of Total Leukocytes by Treatment Group") +
  theme_minimal()

ttest <- t.test(fft_leuk$Total_leukocytes, control_leuk$Total_leukocytes)
print(ttest)


```

## Hematology plots
```{r}
library(ggplot2)
library(dplyr)
library(ggpubr)

meta_cleaned <- read.table("Meta_cleaned.txt", sep = "\t", header = TRUE)

# Add new column 'NEC_incidence' with blank values
meta_cleaned <- cbind(meta_cleaned[, 1:4], NEC_incidence = "", meta_cleaned[, 5:ncol(meta_cleaned)])

# Update the 'NEC_incidence' column based on 'Colon_score'
meta_cleaned$NEC_incidence <- ifelse(meta_cleaned$Colon_score >= 4, "NEC", "No NEC")

# Modify the 'Group' column
meta_cleaned$Group <- gsub("FFT[12]", "FFT", meta_cleaned$Group)
meta_cleaned$Group <- gsub("Control[12]", "Control", meta_cleaned$Group)

# Filter out rows with NA values in the specified columns
filtered_meta <- meta_cleaned %>%
  filter(!is.na(Neutrophiles) & !is.na(Lymphocytes) & !is.na(Monocytes))

# Calculate count of observations per group
count_data <- filtered_meta %>%
  group_by(Group) %>%
  summarize(count = n())

# Define individual colors for each group
group_colors <- c("cornflowerblue", "tomato")


## Neutrophils
# Perform t-test
ttest_neutrophiles <- t.test(Neutrophiles ~ Group, data = filtered_meta)

# Extract the p-value from the t-test result
pvalue_neutrophiles <- format(ttest_neutrophiles$p.value, digits = 3)

# Make a plot
plot_neutrophiles <- ggplot(filtered_meta, aes(x = Group, y = Neutrophiles, fill = Group)) +
  geom_boxplot(alpha = 0.8, show.legend = FALSE) +
  geom_jitter(aes(color = Group), width = 0.2, height = 0, show.legend = FALSE) +
  annotate("text",
    x = count_data$Group,
    y = annotation_y_neutrophiles,
    label = paste("n =", count_data$count),
    vjust = 1) +
  scale_fill_manual(values = group_colors) +
  scale_color_manual(values = c("steelblue", "firebrick3")) +
  ggtitle("Neutrophils") +
  labs(x = "", y = "", fill = "Group", color = "Group", shape = "NEC Incidence") +
  theme_minimal() +
  theme(legend.position = "none",
    plot.margin = margin(10, 10, 30, 10, unit = "pt"),
    text = element_text(size = 12, face = "bold")) +
  geom_text(x = mean(as.numeric(as.factor(filtered_meta$Group))),
    y = min(filtered_meta$Neutrophiles),
    label = paste("t-test p =", pvalue_neutrophiles),
    color = "red",
    size = 4,
    hjust = 0.5,
    vjust = -0.5) +
  coord_cartesian(clip = "off")

# Add labels to the scatter points
plot_neutrophiles <- plot_neutrophiles +
  scale_shape_manual(values = c(16, 17), labels = c("No NEC", "NEC")) +
  labs(shape = "NEC Incidence",
       legend = list(title = "Legend", 
                     labels = c("No NEC: Triangles", "NEC: Circles")))


## Lymphocytes
# Perform a t-test
ttest_lymphocytes <- t.test(Lymphocytes ~ Group, data = filtered_meta)

# Extract the p-value from the t-test result
pvalue_lymphocytes <- format(ttest_lymphocytes$p.value, digits = 3)

# Make a plot
plot_lymphocytes <- ggplot(filtered_meta, aes(x = Group, y = Lymphocytes, fill = Group)) +
  geom_boxplot(alpha = 0.8, show.legend = FALSE) +
  geom_jitter(aes(color = Group), width = 0.2, height = 0, show.legend = FALSE) +
  annotate("text",
    x = count_data$Group,
    y = annotation_y_lymphocytes,
    label = paste("n =", count_data$count),
    vjust = 1) +
  scale_fill_manual(values = group_colors) +
  scale_color_manual(values = c("steelblue", "firebrick3")) +
  ggtitle("Lymphocytes") +
  labs(x = "", y = "", fill = "Group", color = "Group", shape = "NEC Incidence") +
  theme_minimal() +
  theme(legend.position = "none",
    plot.margin = margin(10, 10, 30, 10, unit = "pt"),
    text = element_text(size = 12, face = "bold")) +
  geom_text(x = mean(as.numeric(as.factor(filtered_meta$Group))), y = min(filtered_meta$Lymphocytes),
    label = paste("t-test p =", pvalue_lymphocytes),
    color = "red",
    size = 4,
    hjust = 0.5,
    vjust = -0.5) +
  coord_cartesian(clip = "off")

# Add labels to the scatter points
plot_lymphocytes <- plot_lymphocytes +
  scale_shape_manual(values = c(16, 17), labels = c("No NEC", "NEC")) +
  labs(shape = "NEC Incidence",
       legend = list(title = "Legend", 
                     labels = c("No NEC: Triangles", "NEC: Circles")))


## Monocytes
# Perform a t-test
ttest_monocytes <- t.test(Monocytes ~ Group, data = filtered_meta)

# Extract the p-value from the t-test result
pvalue_monocytes <- format(ttest_monocytes$p.value, digits = 3)

# Make a plot
plot_monocytes <- ggplot(filtered_meta, aes(x = Group, y = Monocytes, fill = Group)) +
  geom_boxplot(alpha = 0.8) +
  geom_jitter(aes(color = Group), width = 0.2, height = 0) +
  annotate("text",
    x = count_data$Group,
    y = annotation_y,
    label = paste("n =", count_data$count),
    vjust = 1) +
  scale_fill_manual(values = group_colors) +
  scale_color_manual(values = c("steelblue", "firebrick3")) +
  ggtitle("Monocytes") +
  labs(x = "", y = "", fill = "Group", color = "Group", shape = "NEC Incidence") +
  theme_minimal() +
  theme(plot.margin = margin(10, 10, 30, 10, unit = "pt"),
    text = element_text(size = 12, face = "bold")) +
  geom_text(x = mean(as.numeric(as.factor(filtered_meta$Group))),y = max(filtered_meta$Monocytes),
    label = paste("t-test p =", pvalue_monocytes),
    color = "red",
    size = 4,
    hjust = 0.5,
    vjust = -0.5) +
  coord_cartesian(clip = "off")

# Add labels to the scatter points
plot_monocytes <- plot_monocytes +
  scale_shape_manual(values = c(16, 17), labels = c("No NEC", "NEC")) +
  labs(shape = "NEC Incidence",
       legend = list(title = "Legend", 
                     labels = c("No NEC: Triangles", "NEC: Circles")))

# Patchwork
# Combine the plots using patchwork
plot_neutrophiles + plot_lymphocytes + plot_monocytes +
  patchwork::plot_layout(widths = 50, heights = 10) +
  patchwork::plot_annotation("Leukocyte concentration from Hematocytic data",
    theme = theme(text = element_text(size = 15, face = "bold"),
                  legend.text = element_text(size = 100)))

# Save the combined plots using ggsave
ggsave("./outputs/banging_hemato.jpeg", device = "jpeg", dpi = 300, height = 10, width = 20)


```
